name: Web Scraper Tracker

on:
  schedule:
    # Yeh cron job har din midnight (UTC) par chalegi. Aap isse change kar sakte hain.
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Aap manually bhi run kar sakte ho

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the web scraper script
        run: |
          python web_scraper_tracker.py
